# install with conda env create -f env.yml
name: "job_opt"
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.12
  - pip
  - google-genai
  - markdown
  - weasyprint
  - python-dotenv
  - pytest
